project:
  type: website
  output-dir: docs

execute:
  # freeze: auto
  echo: false
  warning: false
  
website:
  title: "BeepBoopStats"
  # google-analytics: "UA-121215066-1"
  reader-mode: false
  page-footer: Â© Beep Boop Stats
  # top nav
  navbar:
    pinned: true
    logo: /assets/img/favicons/android-chrome-512x512.png
    search: true
    left:
      # - text: "Home"
      #   file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Contact"
        file: assets/contact/index.qmd

format:
  html:
    theme: 
      light: 
        - pulse
        - assets/css/styles.scss
      dark: 
        - darkly
        - assets/css/styles.scss
    fontsize: 1.1em
    page-layout: full
    toc: true
    toc-depth: 4
    toc-location: left
    toc-expand: 1
    embed-resources: true
    # new options
    toc_float: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show code"

format-links: []
