project:
  type: website
  output-dir: docs

execute:
  # freeze: auto
  echo: false
  warning: false
  
website:
  title: "BeepBoopStats"
  google-analytics: "G-LXSX23EQ95"
  reader-mode: false
  page-footer: Â© Beep Boop Stats
  favicon: /assets/img/favicons/android-chrome-192x192.png
  # top nav
  navbar:
    pinned: true
    logo: /assets/img/favicons/apple-touch-icon.png
    search: true
    left:
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "About"
        file: about.qmd
      - text: "Contact"
        file: assets/contact/index.qmd
    css: assets/css/styles.scss

format:
  html:
    theme: 
      light: 
        - pulse
        - assets/css/styles.scss
      dark: 
        - darkly
        - assets/css/styles.scss
    fontsize: 1.1em
    page-layout: full
    toc: true
    toc-depth: 4
    toc-location: left
    toc-expand: 1
    embed-resources: true
    # new options
    toc_float: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show code"

format-links: []
