project:
  type: website
  output-dir: docs

execute:
  # freeze: auto
  echo: false
  warning: false
  
website:
  title: "IUSSI-NAS DEIJ"
  google-analytics: "G-LXSX23EQ95"
  reader-mode: false
  page-footer: created with ‚ù§ by [BeepBoopStats, LLC](https://www.beepboopstats.com/)
  favicon: /assets/img/favicons/android-chrome-192x192.png
  repo-url: "https://github.com/beepboopstats/iussi-nas-deij"
  repo-actions: ["issue"]
  # top nav
  navbar:
    pinned: true
    logo: /assets/img/favicons/apple-touch-icon.png
    search: true
    left:
      - text: "Outreach Program"
        menu:
          - text: "Overview"
            file: outreach.qmd
          - text: "Turner-Collins Award"
            file: tc_award.qmd
          - text: "Workshop Series"
            file: workshop.qmd
          - text: "Fundraising"
            file: fundraising.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Meet the Committee"
        file: assets/contact/index.qmd
    css: assets/css/styles.scss

format:
  html:
    theme: 
      light: 
        - pulse
        - assets/css/styles.scss
      # dark: 
      #   - darkly
      #   - assets/css/styles.scss
    fontsize: 1.1em
    page-layout: full
    toc: true
    toc-depth: 4
    toc-location: left
    toc-expand: 1
    embed-resources: true
    # new options
    toc_float: true
    code-overflow: wrap
    code-fold: true
    code-summary: "Show code"

format-links: []
